-define(DER_NULL, <<5, 0>>).

-if(?OTP_RELEASE >= 28).
-define(EXPECTED_SIGNATURE_ALGORITHM_PARAMETERS, {asn1_OPENTYPE, ?DER_NULL}).
-else.
-define(EXPECTED_SIGNATURE_ALGORITHM_PARAMETERS, 'NULL').
-endif.
