name: Erlang CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        erlang:
          - "27.3.4"
          - "28.1"

    runs-on: ubuntu-latest
    container:
      image: erlang:${{ matrix.erlang }}

    permissions:
      checks: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do eunit --cover, cover, covertool generate
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2.20.0
      if: (!cancelled())
      with:
        files: |
          _build/test/surefire/*.xml
